Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/nbclient/client.py", line 1265, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mervecoroz/Library/Python/3.11/lib/python/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/nbclient/client.py", line 648, in async_setup_kernel
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/nbclient/client.py", line 703, in async_execute
    await self.async_execute_cell(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/nbclient/client.py", line 1021, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/nbclient/client.py", line 915, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
penguin_total = interpolated_data.groupby('year')['penguin_count'].sum()
plt.bar(penguin_total.index, penguin_total)
plt.xlabel('Year')
plt.ylabel('Total Penguins')
plt.title('Bar Plot of Total Penguin Count per Year')
plt.xticks(penguin_total.index, rotation=45)
plt.grid(axis='y')
plt.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[6], line 2[0m
[1;32m      1[0m penguin_total [38;5;241m=[39m interpolated_data[38;5;241m.[39mgroupby([38;5;124m'[39m[38;5;124myear[39m[38;5;124m'[39m)[[38;5;124m'[39m[38;5;124mpenguin_count[39m[38;5;124m'[39m][38;5;241m.[39msum()
[0;32m----> 2[0m [43mplt[49m[38;5;241m.[39mbar(penguin_total[38;5;241m.[39mindex, penguin_total)
[1;32m      3[0m plt[38;5;241m.[39mxlabel([38;5;124m'[39m[38;5;124mYear[39m[38;5;124m'[39m)
[1;32m      4[0m plt[38;5;241m.[39mylabel([38;5;124m'[39m[38;5;124mTotal Penguins[39m[38;5;124m'[39m)

[0;31mNameError[0m: name 'plt' is not defined
NameError: name 'plt' is not defined

